package com.greendao.manager;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.parachute.administrator.DATAbase.greendao.TaskEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK_ENTITY".
*/
public class TaskEntityDao extends AbstractDao<TaskEntity, Long> {

    public static final String TABLENAME = "TASK_ENTITY";

    /**
     * Properties of entity TaskEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UnitName = new Property(1, String.class, "unitName", false, "UNIT_NAME");
        public final static Property GasePumpNumber = new Property(2, String.class, "gasePumpNumber", false, "GASE_PUMP_NUMBER");
        public final static Property PeopleName = new Property(3, String.class, "peopleName", false, "PEOPLE_NAME");
        public final static Property _IsCompleteTask = new Property(4, boolean.class, "_IsCompleteTask", false, "__IS_COMPLETE_TASK");
        public final static Property TaskHaveGetData = new Property(5, int.class, "taskHaveGetData", false, "TASK_HAVE_GET_DATA");
        public final static Property GreateTaskTime = new Property(6, String.class, "greateTaskTime", false, "GREATE_TASK_TIME");
        public final static Property Csff = new Property(7, String.class, "csff", false, "CSFF");
        public final static Property By1 = new Property(8, String.class, "by1", false, "BY1");
        public final static Property By2 = new Property(9, String.class, "by2", false, "BY2");
        public final static Property By3 = new Property(10, String.class, "by3", false, "BY3");
        public final static Property By4 = new Property(11, String.class, "by4", false, "BY4");
        public final static Property By5 = new Property(12, String.class, "by5", false, "BY5");
        public final static Property By6 = new Property(13, String.class, "by6", false, "BY6");
        public final static Property By7 = new Property(14, String.class, "by7", false, "BY7");
        public final static Property By8 = new Property(15, String.class, "by8", false, "BY8");
        public final static Property By9 = new Property(16, String.class, "by9", false, "BY9");
        public final static Property By10 = new Property(17, String.class, "by10", false, "BY10");
        public final static Property By11 = new Property(18, String.class, "by11", false, "BY11");
        public final static Property By12 = new Property(19, String.class, "by12", false, "BY12");
    }


    public TaskEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TaskEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UNIT_NAME\" TEXT," + // 1: unitName
                "\"GASE_PUMP_NUMBER\" TEXT," + // 2: gasePumpNumber
                "\"PEOPLE_NAME\" TEXT," + // 3: peopleName
                "\"__IS_COMPLETE_TASK\" INTEGER NOT NULL ," + // 4: _IsCompleteTask
                "\"TASK_HAVE_GET_DATA\" INTEGER NOT NULL ," + // 5: taskHaveGetData
                "\"GREATE_TASK_TIME\" TEXT," + // 6: greateTaskTime
                "\"CSFF\" TEXT," + // 7: csff
                "\"BY1\" TEXT," + // 8: by1
                "\"BY2\" TEXT," + // 9: by2
                "\"BY3\" TEXT," + // 10: by3
                "\"BY4\" TEXT," + // 11: by4
                "\"BY5\" TEXT," + // 12: by5
                "\"BY6\" TEXT," + // 13: by6
                "\"BY7\" TEXT," + // 14: by7
                "\"BY8\" TEXT," + // 15: by8
                "\"BY9\" TEXT," + // 16: by9
                "\"BY10\" TEXT," + // 17: by10
                "\"BY11\" TEXT," + // 18: by11
                "\"BY12\" TEXT);"); // 19: by12
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TaskEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String unitName = entity.getUnitName();
        if (unitName != null) {
            stmt.bindString(2, unitName);
        }
 
        String gasePumpNumber = entity.getGasePumpNumber();
        if (gasePumpNumber != null) {
            stmt.bindString(3, gasePumpNumber);
        }
 
        String peopleName = entity.getPeopleName();
        if (peopleName != null) {
            stmt.bindString(4, peopleName);
        }
        stmt.bindLong(5, entity.get_IsCompleteTask() ? 1L: 0L);
        stmt.bindLong(6, entity.getTaskHaveGetData());
 
        String greateTaskTime = entity.getGreateTaskTime();
        if (greateTaskTime != null) {
            stmt.bindString(7, greateTaskTime);
        }
 
        String csff = entity.getCsff();
        if (csff != null) {
            stmt.bindString(8, csff);
        }
 
        String by1 = entity.getBy1();
        if (by1 != null) {
            stmt.bindString(9, by1);
        }
 
        String by2 = entity.getBy2();
        if (by2 != null) {
            stmt.bindString(10, by2);
        }
 
        String by3 = entity.getBy3();
        if (by3 != null) {
            stmt.bindString(11, by3);
        }
 
        String by4 = entity.getBy4();
        if (by4 != null) {
            stmt.bindString(12, by4);
        }
 
        String by5 = entity.getBy5();
        if (by5 != null) {
            stmt.bindString(13, by5);
        }
 
        String by6 = entity.getBy6();
        if (by6 != null) {
            stmt.bindString(14, by6);
        }
 
        String by7 = entity.getBy7();
        if (by7 != null) {
            stmt.bindString(15, by7);
        }
 
        String by8 = entity.getBy8();
        if (by8 != null) {
            stmt.bindString(16, by8);
        }
 
        String by9 = entity.getBy9();
        if (by9 != null) {
            stmt.bindString(17, by9);
        }
 
        String by10 = entity.getBy10();
        if (by10 != null) {
            stmt.bindString(18, by10);
        }
 
        String by11 = entity.getBy11();
        if (by11 != null) {
            stmt.bindString(19, by11);
        }
 
        String by12 = entity.getBy12();
        if (by12 != null) {
            stmt.bindString(20, by12);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TaskEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String unitName = entity.getUnitName();
        if (unitName != null) {
            stmt.bindString(2, unitName);
        }
 
        String gasePumpNumber = entity.getGasePumpNumber();
        if (gasePumpNumber != null) {
            stmt.bindString(3, gasePumpNumber);
        }
 
        String peopleName = entity.getPeopleName();
        if (peopleName != null) {
            stmt.bindString(4, peopleName);
        }
        stmt.bindLong(5, entity.get_IsCompleteTask() ? 1L: 0L);
        stmt.bindLong(6, entity.getTaskHaveGetData());
 
        String greateTaskTime = entity.getGreateTaskTime();
        if (greateTaskTime != null) {
            stmt.bindString(7, greateTaskTime);
        }
 
        String csff = entity.getCsff();
        if (csff != null) {
            stmt.bindString(8, csff);
        }
 
        String by1 = entity.getBy1();
        if (by1 != null) {
            stmt.bindString(9, by1);
        }
 
        String by2 = entity.getBy2();
        if (by2 != null) {
            stmt.bindString(10, by2);
        }
 
        String by3 = entity.getBy3();
        if (by3 != null) {
            stmt.bindString(11, by3);
        }
 
        String by4 = entity.getBy4();
        if (by4 != null) {
            stmt.bindString(12, by4);
        }
 
        String by5 = entity.getBy5();
        if (by5 != null) {
            stmt.bindString(13, by5);
        }
 
        String by6 = entity.getBy6();
        if (by6 != null) {
            stmt.bindString(14, by6);
        }
 
        String by7 = entity.getBy7();
        if (by7 != null) {
            stmt.bindString(15, by7);
        }
 
        String by8 = entity.getBy8();
        if (by8 != null) {
            stmt.bindString(16, by8);
        }
 
        String by9 = entity.getBy9();
        if (by9 != null) {
            stmt.bindString(17, by9);
        }
 
        String by10 = entity.getBy10();
        if (by10 != null) {
            stmt.bindString(18, by10);
        }
 
        String by11 = entity.getBy11();
        if (by11 != null) {
            stmt.bindString(19, by11);
        }
 
        String by12 = entity.getBy12();
        if (by12 != null) {
            stmt.bindString(20, by12);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TaskEntity readEntity(Cursor cursor, int offset) {
        TaskEntity entity = new TaskEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // unitName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // gasePumpNumber
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // peopleName
            cursor.getShort(offset + 4) != 0, // _IsCompleteTask
            cursor.getInt(offset + 5), // taskHaveGetData
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // greateTaskTime
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // csff
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // by1
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // by2
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // by3
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // by4
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // by5
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // by6
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // by7
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // by8
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // by9
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // by10
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // by11
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19) // by12
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TaskEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUnitName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGasePumpNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPeopleName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.set_IsCompleteTask(cursor.getShort(offset + 4) != 0);
        entity.setTaskHaveGetData(cursor.getInt(offset + 5));
        entity.setGreateTaskTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCsff(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBy1(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBy2(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBy3(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setBy4(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setBy5(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBy6(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setBy7(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setBy8(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setBy9(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setBy10(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setBy11(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setBy12(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TaskEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TaskEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TaskEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
